/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125TeamRouteImport } from './routes/{-$locale}/team'
import { Route as Char123LocaleChar125PricingRouteImport } from './routes/{-$locale}/pricing'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125TeamRoute =
  Char123LocaleChar125TeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125PricingRoute =
  Char123LocaleChar125PricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/team': typeof Char123LocaleChar125TeamRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/team': typeof Char123LocaleChar125TeamRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/team': typeof Char123LocaleChar125TeamRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/auth'
    | '/privacy'
    | '/{-$locale}'
    | '/{-$locale}/contact'
    | '/{-$locale}/pricing'
    | '/{-$locale}/team'
    | '/{-$locale}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/auth'
    | '/privacy'
    | '/{-$locale}/contact'
    | '/{-$locale}/pricing'
    | '/{-$locale}/team'
    | '/{-$locale}'
  id:
    | '__root__'
    | '/admin'
    | '/auth'
    | '/privacy'
    | '/{-$locale}'
    | '/{-$locale}/contact'
    | '/{-$locale}/pricing'
    | '/{-$locale}/team'
    | '/{-$locale}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/team': {
      id: '/{-$locale}/team'
      path: '/team'
      fullPath: '/{-$locale}/team'
      preLoaderRoute: typeof Char123LocaleChar125TeamRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/pricing': {
      id: '/{-$locale}/pricing'
      path: '/pricing'
      fullPath: '/{-$locale}/pricing'
      preLoaderRoute: typeof Char123LocaleChar125PricingRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
  }
}

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125PricingRoute: typeof Char123LocaleChar125PricingRoute
  Char123LocaleChar125TeamRoute: typeof Char123LocaleChar125TeamRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
  Char123LocaleChar125PricingRoute: Char123LocaleChar125PricingRoute,
  Char123LocaleChar125TeamRoute: Char123LocaleChar125TeamRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
